#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/openhappd
CONFIG=openhapp

load_config() {
	config_load "$CONFIG"
	config_get_bool ENABLED main enabled 1
	config_get_bool AUTOSTART main autostart 1
}

start_service() {
	load_config

	[ "$ENABLED" = "1" ] || return 0
	[ "$AUTOSTART" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG"
}

reload_service() {
	stop
	start
}
