#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/openhapp-ubus
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
